### ISSUE TITLE
Not able to run, exceptions occur

### ISSUE THREAD

**Issue by tielei** [iBicha/WebRTC-for-Unity#2] opened 2017-08-18 07:48 UTC
I built an APK with Unity 5.6.1, but it throws the following exception when running on Android phones:

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ibicha.webrtc/com.ibicha.webrtc.WebRTCActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ibicha.webrtc.WebRTCActivity" on path: DexPathList[[zip file "/data/app/com.ibicha.webrtc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ibicha.webrtc-1/lib/arm, /data/app/com.ibicha.webrtc-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
 at android.app.ActivityThread.access$900(ActivityThread.java:153)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5438)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ibicha.webrtc.WebRTCActivity" on path: DexPathList[[zip file "/data/app/com.ibicha.webrtc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ibicha.webrtc-1/lib/arm, /data/app/com.ibicha.webrtc-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
 ... 9 more
 Suppressed: java.lang.ClassNotFoundException: com.ibicha.webrtc.WebRTCActivity
  at java.lang.Class.classForName(Native Method)
  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
  ... 12 more
 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by iBicha** [comment] 2017-08-18 17:16
Seems like an android manifest issue.

Since we run `startActivityForResult `to get permission to record the screen, `onActivityResult` needed to be overriden to get the result from it, and therefore why webrtc needed to extend `UnityPlayerActivity`.
But I didn't pay a lot of attentions to every attribute in the main manifest.

I did not face this problem at all. But I made some changes to the manifest, in hope that the activity is found and launched correctly.

Please pull the new code, and if the problem persists, please leave these info:
Current platform and android build tools?
Any other android plugins within the same project?

**Comment by tielei** [comment] 2017-08-21 03:14
It still not works for me.
I think my build process/method is not correct. I generated the APK with Unity 5.6.1 (File->Build Settings->Switch Platform to Android->Click Build Button).

If I otherwise choose to export an Android gradle project and build an APK from it, I got the same failure. In the newly exported project, the 'webrtc-android' directory is not there. So I think the cause is that the 'webrtc-android' directory is not bundled into the final APK. 

Am I  in the correct way to build this project?

**Comment by iBicha** [comment] 2017-08-21 15:11
That is the correct way to build, no need to export the gradle project.
Also, 'webrtc-android' is already built-in as a library, found in Assets/WebRTCForUnity/WebRTC/Plugins/Android/webrtc-release.aar
So make sure the file is there

**Comment by tielei** [comment] 2017-08-22 05:53
Thanks! I manually copied the aar file to the expected directory, and it works! 

I think there may be some compatibility issues with the build.gradle files. I found the copyDebugAarToUnity & copyReleaseAarToUnity task do not work for me :(

**Comment by tielei** [comment] 2017-08-22 15:18
Hi, @iBicha , I am experimenting with another feature based on your repo. My goal is not only to send the camera raw texture to Unity, but also I want to do some post-processing with the texture captured from camera, such as filters or beautifying the captured image. But I found the Unity rendering may be conflict with my own OpenGL ES rendering operations.  To verify, I hooked the code of this repo to draw a very simple triangle using OpenGL ES 2.0 and modified the texture format to RGBA32, accordingly. This triangle will be expected to shown on Unity GameObjects if there is no any conflict between my drawing and the Unity internal rendering. However, it does not work, with many GL_INVALID_OPERATION errors. My experiment code is here: https://github.com/tielei/WebRTC-for-Unity/commit/638cb96d3c35e532eb5dc752e3394bcea2cae0f2 . So I believe that it is not possible to mix native OpenGL ES 2.0 commands with Unity. I do not know whether this conclusion is truth. Do you have any ideas about this point? Thank you!

**Comment by iBicha** [comment] 2017-08-22 15:45
Hi @tielei 
The reason for the GL_INVALID_OPERATION errors is mainly because of threading. You are trying to draw for a thread that is different than Unity's rendering thread (callback.renderFrame is called on a capturing thread). Another thing to consider is contexts. Unity's context and and webrtc's are different (even though they share resources such as textues)
I suggest that you open a seperate issue for this if you are really seeking help, and maybe someone (or myself) will try to figure out when I find some time for it.

Back to the main issue, building the apk originally does not trigger rebuilding the aar library. (for obvious reasons, no need to rebuild it if there isnt any changes to the java files) but the truth is, gradle also have a mechanism to detect changes, and the rebuild is super fast when there isn't any. So building the library everytime we build the unity project doesnt add significant overhead.

Another thing was being sketchy, is the tasks where not copying the aar to unity. they where executed **before** the build is finished, and before the file existed. So one needed to execute the build twice, or just copy it manually.

I will push a fix to this, where I copy the aar from an editor script rather than gradle, and also will trigger the aar build before the unity project build, which is an expected behaviour.

**Comment by iBicha** [comment] 2017-08-22 16:02
I will close this for now, will open again if the issue persists.

**Closed** 2017-08-22 16:02 UTC
Labels: bug, need-more-information

**Comment by tielei** [comment] 2017-08-23 12:31
Hi, @iBicha , your comments are very reasonable and helpful :)
Now I am trying to use a different EGLContext from the Unity's one in another thread for OpenGL ES rendering. Thanks very much!

By the way, I have to do post processing in Android instead of in Unity, since a lot of existing code can be reused in my project.
